# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170404_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(blank=True, choices=[('d', 'draft'), ('p', 'published'), ('w', 'withdrawn')], help_text='Optional 입니다.', max_length=1),
        ),
    ]
